

SHELL := /bin/bash
PWD := $(shell pwd)
USER_BIN := $(HOME)/bin

ubuntu.neovim:
	@curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
	@chmod +x nvim.appimage
	@mv nvim $(USER_BIN)

